apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: default
spec:
  type: ExternalName
  # This is where the magic happens. Make sure that the 
  # service name, namespace name etc are accurate.
  # This is the format: "service-name.namespace-name.svc.cluster.local"
  externalName: app1-svc.app1.svc.cluster.local
  ports:
  - port: 80
